---
title: "Estimación puntual"
output: html_document # pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
options(scipen = 999)

set.seed(0)

r = 10
p = 0.7
n = 100

## X_i: cantidad de veces que se aplicó la estrategia en el i-esimo juego
X = rnbinom(n, size = r, prob= p) + r
E_X = mean(X)
var_X = var(X)*(n-1)/n

r_hat = round(E_X^2/(var_X+ E_X),2)
p_hat = round(E_X/(var_X +E_X),3)

# estimacion de la esperanza de p_hat
Hat_P =c()
for (i in 1:1000) {
   X = rnbinom(n, size = r, prob= p) + r
   E_X = mean(X)
   var_X = var(X)*(n-1)/n
   Hat_P[i] = E_X/(var_X +E_X)
}
E_phat = mean(Hat_P)

# Intervalo Asintotico

alpha = 0.05
z_aover2 = qnorm(1-alpha/2)

raiz = sqrt(E_X*(E_X - r)/(r*n))

left = r/(E_X + raiz*z_aover2)
right = r/(E_X -raiz*z_aover2)



```


Ejercicio 1
---------

* Considere un juego de computadora en el que la estrategia seguida por el adversario es siempre la misma de tal forma que la probabilidad de anotar es fija dada por $p$. La computadora dá por terminado el juego cuando se lograron $r$ éxitos por parte del adversario pero ésta sólo informa la cantidad de jugadas realizadas. Para estimar cual es la probabilidad de anotar $p$ y con cuántos éxitos $r$ se termina un juego decidimos jugarlo $`r n`$ veces y anotar los resultados que arroja la compu. Así las observaciones son:


<table>
<tr>
`r X[1:25]`
</tr>
<tr>
`r X[26:50]` </tr>
<tr>
`r X[51:75]` 
</tr>
<tr>
`r X[76:100]`
</tr>
</table>


Modelamos el problema con una distribución Binomial Negativa $BN(r,p)$ con $r,p$ parámetros a estimar.

Los estimadores de momentos de $p$ y $r$ son:

$$
\hat{p}_M = \displaystyle\frac{\bar{X_n}}{\frac{1}{n}\sum_{i=1}^n(X_i - \bar{X_n})^2 +\bar{X_n}}
$$
$$
\hat{r}_M = \displaystyle\frac{\bar{X_n}^2}{\frac{1}{n}\sum_{i=1}^n(X_i - \bar{X_n})^2 +\bar{X_n}}
$$

Si $n = `r n`$ obtenemos para estas observaciones el promedio muestral y la varianza empírica son $\bar{X}_n = `r E_X`$, $\frac{1}{n}\sum_{i=1}^n(X_i - \bar{X_n})^2 = `r var_X`$

Las estimaciones de $r$ y $p$ basadas en los estimadores de momentos son:

$$
\hat{r} = `r r_hat`, \hat{p} = `r p_hat`
$$ 
<h3> Intervalo de confianza de nivel asintótico $1-\alpha=`r 1-alpha`$</h3>

Si suponemos que $X_1,\dots,X_{`r n`}\sim BN(10, p)$, se obtiene usando TCL y Slutski un intervalo de confianza de nivel asintótico $1-\alpha$  para el parámetro $p$ :
$$
\left[\frac{`r r`}{\bar{X}_n + \sqrt{\frac{\bar{X}_n(\bar{X}_n - `r r`)}{`r r`n}}z_{\alpha/2}},\frac{`r r`}{\bar{X}_n - \sqrt{\frac{\bar{X}_n(\bar{X}_n - `r r`)}{`r r`n}}z_{\alpha/2}}\right ] 
$$
Con las observaciones tenemos que con confianza $`r 1-alpha`$ el parámtro $p \in [`r left`, `r right`]$