---
title: "Estimación puntual e Intervalo de confianza"
output: html_document # pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
options(scipen = 999)

#set.seed(1)

n = 500
theta = 100

U = runif(n, min = 0, max = 1)
Y = round(theta/((1-U)^(1/3)),1) + rnorm(n, mean=0, sd =0.001)

E_Y = mean(Y) # es el barra(Y_n)
var_Y = var(Y)*(n-1)/n

theta_MV = min(Y)

theta_M = 2*mean(Y)/3

##### Intervalo de confianza

# intervalo 1 armado dejando a la derecha un area de alpha
alpha = 0.05
q_alpha = (1/alpha)^(1/(3*n))

l1 = theta_MV/q_alpha
r1 = theta_MV

# Intervalo 2 aramado dejando a cada lado un area de alpha/2:

q1 = (2/(2-alpha))^(1/(3*n))
q2 = (2/alpha)^(1/(3*n))

l2 = theta_MV/q2
r2 = theta_MV/q1


# Intervalo de nivel asintotico:
z_aover2 = qnorm(1-alpha/2, 0, 1)

l_asin = theta_M/(1+z_aover2/sqrt(3*n))
r_asin = theta_M/(1-z_aover2/sqrt(3*n))

## usando slutski
l_sluts = theta_M*(1-sqrt(3/n)*z_aover2)
r_sluts = theta_M*(1+sqrt(3/n)*z_aover2)



```


<strong><h2> Ejercicio </h2></strong>

* El ingreso anual de una persona de un cierto sector de la población es una variable aleatoria $Y$ que se puede modelar con la siguiente densidad 
$$
f(y; \theta) = \frac{3\theta^3}{y^4}I_{[\theta, +\infty]}(y)
$$

Se realiza una encuesta sobre los ingresos a $`r n`$ personas de dicho sector obteniéndose como resultado las siguientes observaciones en miles de dolares

<table>
<tr>
`r Y[1:25]`
</tr>
<tr>
`r Y[26:50]` 
</tr>
<tr>
`r Y[51:75]` 
</tr>
<tr>
`r Y[76:100]`
</tr>
</table>


De donde se obtiene que 
$$\bar{Y}_n = `r E_Y` \qquad  \text{y } \min_{1\leq i\leq n}(Y_i) = `r theta_MV`
$$

A partir de estas observaciones dar una estimación del parámetro $\theta$ basado en el estimador de máxima verosimilutd $\hat{\theta}_{MV}$



<strong><h2> Solución: </h2> </strong>

La función de verosimilitud es 
$$
l(\theta) = \displaystyle\prod_{i=1}^{n}f(y_i;\theta) = \begin{cases}
\prod_{i=1}^{n}\frac{3\theta^3}{y_i^4},  & si \quad \theta < \min_{i}(Y_i)\\
0 & sino
\end{cases}
$$

El estimador de máxima verosimilitud de $\theta$ está dado por $\hat{\theta}_{MV} = \displaystyle\min_{1\leq i\leq n}(Y_i)$.

Usando las observaciones obtenemos una estimación de $\hat{\theta}=`r theta_MV`$.


<h3>Bonus </h3>

el estimador de momentos de $\theta$ es: $\hat{\theta}_M = \frac{2\bar{Y}_n}{3}$

esto sale de calcular la esperanza $E(Y)=\int_{\theta}^{+\infty}\frac{y3\theta^3}{y^4}dy = \frac{3}{2}\theta$.

Luego la estimación de $\theta$ basada en momentos es: $`r theta_M`$

<h2> Intervalo de confianza para $\theta$</h2>

Un intervalo de confianza de nivel $1-\alpha = `r 1-alpha`$ es:
$$
I = \left[\frac{\min(Y_i)}{q_{\alpha}}, \min(Y_i)\right]
$$
con $q_{\alpha}$ el número que satistace que $P(Y > q_{\alpha})=\alpha$. 

Usando las observaciones tenemos un intervalo estimado de:
$$
I = [`r l1`, `r r1`]
$$
La longitud de este intervalo estimado es: $`r r1-l1`$.

Otro intervalo de confianza de nivel $`r 1-alpha`$ es el obtenido al dejar igual area de cada lado

$$
I = \left[\frac{\min(Y_i)}{q_2}, \frac{\min(Y_i)}{q_1}\right]
$$
donde $q_1, q_2$ son los que acumulanm una probabilidad de $\alpha/2$ para la izquierda y para la derecha respectivamente. 

Usando las observaciones obtenemos el siguiente intervalo estimado:

$$
I = [`r l2`, `r r2`]
$$

La longitud de este intervalo estimado es $`r r2-l2`$.

<h3> Intervalo de nivel asintótico </h3>

Un intervalo de confianza de nivel asintótico $1 - \alpha = `r 1-alpha`$ surge de la siguiente observación: Por el Teorema Central del Límite $\frac{\bar{Y}_n - E(\bar{Y}_n)}{\sqrt{Var(\bar{Y}_n)}}$ sigue una distribución aproximadamente normal $\mathcal{N}(0,1)$. 
Como 
$$
E(\bar{Y}_n)=E(Y_1) = \frac{3}{2}\theta
$$
$$
Var(\bar{Y}_n) = \frac{1}{n}Var(Y_1) = \frac{3}{4n}\theta^2
$$
entonces
$$
\frac{2\sqrt{n}(\bar{Y}_n - 3\theta/2)}{\sqrt{3}\theta} \approx \mathcal{N}(0,1)
$$
Luego, 
$$
P\left(-z_{\alpha/2}\leq \frac{2\sqrt{n}(\bar{Y}_n - 3\theta/2)}{\sqrt{3}\theta}\leq z_{\alpha/2}\right)\approx 1-\alpha
$$

con $z_{\alpha/2}$ tal que $P(Z>z_{\alpha/2}) =\alpha/2$ con $Z\sim \mathcal{N}(0,1)$.
Con las observaciones , el intervalo estimado es: $$[`r l_asin`, `r r_asin`]$$
cuya longitud es $`r r_asin -l_asin`$.

<h4> Otro intervalo asintótico posible se obtiene usando el Teorema de Slutski</h4>

Chequear que con las observaciones dadas un intervalo de confianza de nivel asintótico $`r 1-alpha`$ es
$$
[`r l_sluts` , `r r_sluts`]
$$

